blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, 
                      document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()
    
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    
    def __str__(self):
        return self.title
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs' : blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects' : projects})

blog/templates/blog/all_blogs.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center"> Blog</h1>
<h4 class="text-center">Luiz has {{ blogs.count }} post{{ blogs.count|pluralize }}</h4>
<br>
{% for blog in  blogs %}

<div class="row justify-content-center my-3">
  <div class="col-md-10">

        <a href="{% url 'blog:detail' blog.id %}">
            <h5>{{ blog.title }}</h5>
        </a>
        <p>{{ blog.date|date:'d M Y' }}</p> 
        <p>{{ blog.description|striptags|truncatechars:100 }}</p>
    </div>
</div>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <h1> {{ blog.title }}</h1>
    <h5>{{ blog.date|date:'d M Y' }}</h5>
    <p>{{ blog.description|safe }}</p>
   </div>
</div>
{% endblock %}

portfolio/templates/base.html
<!doctype html>
<html lang="en">
  <head>
  
    {% load static %}
       
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link rel="icon" type="image/png" href="{% static 'portfolio/Minha_foto_Facebook.jpg' %}">

    <title>My Portfolio</title>
  </head>
  <body>
  
  
  {% load static %}
  
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark h5">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
            <a class="nav-link" aria-current="page" href="{% static 'portfolio/Fake_CV.pdf' %}" target="_blank">Resume</a>
            <a class="nav-link" href="https://www.linkedin.com/feed/" target="_blank">LinkedIn</a>
            <a class="nav-link btn btn-primary" role="button" href="{% url 'blog:all_blogs' %}"> Blog </a>
          </div>
        </div>
      </div>
    </nav>

 {% block content %} {% endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/home.html
{% extends 'base.html' %}

{% block content %}

     {% load static %}
    <h1 class="text-center"> My personal portfolio - Feb 23rd, 2021</h1>
    <br>
    <img class="rounded mx-auto d-block" src="{% static 'portfolio/Minha_foto_Facebook.jpg' %}"  height=370 width=300>
    <br>
    <h2 class="text-center">Luiz Carlos Pellegrini</h2>
    <br>
    
    <div class="row">
        
        {% for project in  projects %}
        
            <div class="col-lg-4 col-md-6">
                <h3>{{ project.title }}</h3>
                <p>{{ project.description }}</p>
                <img src={{ project.image.url }} height=200 width=300>
                <br>
                {% if project.url %}
                <a href='{{ project.url }}' target="_blank"> Link</a>
                {% endif %}
                <br>
            </div>
        
        {% endfor %}
    
     </div>

{% endblock %}